title:  <p align="center"> Dhanashree Bose </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="www.linkedin.com/in/dhanashreebose">LinkedIn</a> |
  <a href="https://github.com/DhanashreeBose">Github</a>
  
  <br>
  I'm working on Data Science, AWS cloud, Machine learning , NLP and Deep Learning related problems.
  <br>
  </p>










theme: jekyll-theme-minimal
